//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppLicense
    {
        public int LicenseId { get; set; }
        public string LicenseKey { get; set; }
        public Nullable<System.DateTime> LicenseDate { get; set; }
        public Nullable<System.DateTime> LicenseExpiryDate { get; set; }
        public string LicenseRemarks { get; set; }
        public Nullable<bool> LicenseStatus { get; set; }
    }
}
