//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttDaily
    {
        public int DailyId { get; set; }
        public System.DateTime DailyDate { get; set; }
        public bool DailyStatus { get; set; }
        public Nullable<System.DateTime> DailyCreatedAt { get; set; }
    }
}
