//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendaceLog
    {
        public long DeviceDataId { get; set; }
        public string MachineId { get; set; }
        public string IPAddress { get; set; }
        public int EnrollNumber { get; set; }
        public Nullable<int> VerifyMode { get; set; }
        public Nullable<int> InOutMode { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<System.TimeSpan> LogTime { get; set; }
        public Nullable<int> WorkCode { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public int AttTypeId { get; set; }
        public Nullable<bool> ReadStatus { get; set; }
        public Nullable<System.DateTime> ReadBatchNumber { get; set; }
    }
}
