//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendaceDevice
    {
        public int DeviceId { get; set; }
        public string DeviceName { get; set; }
        public string DeviceIP { get; set; }
        public Nullable<int> DevicePort { get; set; }
        public string DevicePassword { get; set; }
        public Nullable<int> DeviceMachineNo { get; set; }
        public Nullable<System.TimeSpan> DeviceFetchStartTime { get; set; }
        public Nullable<System.TimeSpan> DeviceFetchEndTime { get; set; }
        public Nullable<System.DateTime> DeviceLastImportDate { get; set; }
        public Nullable<bool> DeviceStatus { get; set; }
        public Nullable<bool> DeviceDataDelete { get; set; }
        public int DeviceType { get; set; }
    }
}
