//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendaceDaily
    {
        public long AttId { get; set; }
        public int AttEmpCode { get; set; }
        public Nullable<int> AttOfficeId { get; set; }
        public Nullable<int> AttJobHistoryId { get; set; }
        public Nullable<System.DateTime> AttDate { get; set; }
        public string AttDateNp { get; set; }
        public Nullable<System.DateTime> AttCheckIn { get; set; }
        public Nullable<System.DateTime> AttCheckOut { get; set; }
        public Nullable<int> AttShiftId { get; set; }
        public Nullable<System.TimeSpan> AttShiftStart { get; set; }
        public Nullable<System.TimeSpan> AttShiftEnd { get; set; }
        public Nullable<bool> IsAbsent { get; set; }
        public Nullable<byte> PayableDay { get; set; }
        public Nullable<bool> IsWeekend { get; set; }
        public Nullable<int> IsHoliday { get; set; }
        public Nullable<int> IsOfficialVisit { get; set; }
        public Nullable<int> IsLeave { get; set; }
        public Nullable<bool> IsTraining { get; set; }
        public string AttRemarks { get; set; }
    }
}
