//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calender
    {
        public int cal_id { get; set; }
        public int nepali_year { get; set; }
        public Nullable<int> month_code { get; set; }
        public Nullable<System.DateTime> eng_start_date { get; set; }
        public Nullable<int> no_days { get; set; }
        public string eng_end_date { get; set; }
    }
}
