//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalenderMonth
    {
        public int MonthId { get; set; }
        public int MonthCode { get; set; }
        public string MonthNameNp { get; set; }
        public string MonthNameEn { get; set; }
        public Nullable<int> PayrollMonthIndex { get; set; }
    }
}
