//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Darbandi
    {
        public int DarbandiId { get; set; }
        public Nullable<int> DarbandiDesgId { get; set; }
        public Nullable<int> DarbandiOfficeId { get; set; }
        public int DarbandiNumber { get; set; }
        public string DarbandiType { get; set; }
        public Nullable<System.DateTime> DarbandiDate { get; set; }
        public string DarbandiRemarks { get; set; }
    }
}
