//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Designation()
        {
            this.EmployeeJobHistories = new HashSet<EmployeeJobHistory>();
            this.EmployeePrizes = new HashSet<EmployeePrize>();
            this.Employees = new HashSet<Employee>();
            this.EmpTrainings = new HashSet<EmpTraining>();
            this.PayrollSalaryMasterSheets = new HashSet<PayrollSalaryMasterSheet>();
        }
    
        public int DsgId { get; set; }
        public string DsgName { get; set; }
        public int DsgParentId { get; set; }
        public string DesgCode { get; set; }
        public string DesgShortCode { get; set; }
        public Nullable<int> DesgOrder { get; set; }
        public Nullable<bool> LeaveRecommendation { get; set; }
        public Nullable<bool> LeaveApprove { get; set; }
        public Nullable<bool> AttendanceRecommendation { get; set; }
        public Nullable<bool> AttendanceApprove { get; set; }
        public Nullable<int> DesgMaxPeriodDays { get; set; }
        public Nullable<int> DesgLevelId { get; set; }
        public decimal DesgSalary { get; set; }
        public decimal DesgPerGradeAmount { get; set; }
        public Nullable<int> DesgMaxGrade { get; set; }
        public decimal DesgSpecialAllowances { get; set; }
        public decimal DesgDressAmount { get; set; }
        public decimal DesgOtherAllowance { get; set; }
        public decimal DesgDearnessAllowance { get; set; }
        public Nullable<decimal> DesgTotalMonthlySalary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeJobHistory> EmployeeJobHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePrize> EmployeePrizes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpTraining> EmpTrainings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollSalaryMasterSheet> PayrollSalaryMasterSheets { get; set; }
    }
}
