//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePrize
    {
        public int PrizeId { get; set; }
        public Nullable<int> PrizeEmpCode { get; set; }
        public string PrizeName { get; set; }
        public string PrizeType { get; set; }
        public int PrizeDesignationId { get; set; }
        public Nullable<System.DateTime> PrizeDate { get; set; }
        public string PrizeDetails { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Designation Designation { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
