//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeBank
    {
        public int Id { get; set; }
        public Nullable<int> EmpCode { get; set; }
        public Nullable<int> BankId { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<bool> AccountPrimary { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
