//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeVisit
    {
        public int VisitId { get; set; }
        public int VisitEmpCode { get; set; }
        public int VisitCoutryId { get; set; }
        public string VisitCity { get; set; }
        public Nullable<System.DateTime> VisitStartDate { get; set; }
        public Nullable<System.DateTime> VisitEndDate { get; set; }
        public int EmpDesignationId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
