//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public int DetailsID { get; set; }
        public int EmpCode { get; set; }
        public string EmpAppointmentAdvNumber { get; set; }
        public Nullable<System.DateTime> EmpDob { get; set; }
        public Nullable<System.DateTime> EmpMarriageAnniversary { get; set; }
        public Nullable<int> EmpEthnicityDid { get; set; }
        public Nullable<int> EmpReligionId { get; set; }
        public string EmpBloodGroup { get; set; }
        public string EmpPANNumber { get; set; }
        public string EmpCITNumber { get; set; }
        public string EmpPFNumber { get; set; }
        public string EmpDrivingLicenseNumber { get; set; }
        public string EmpPassportNumber { get; set; }
        public Nullable<System.DateTime> EmpAgeRetireDate { get; set; }
        public string EmpHuliya { get; set; }
        public string EmpOfficeEmail { get; set; }
        public string EmpPersonalEmail { get; set; }
        public string EmpOfficePhone { get; set; }
        public string EmpHomePhone { get; set; }
        public string EmpPAddress { get; set; }
        public string EmpTAddress { get; set; }
        public string EmpMobileNumber { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactRelation { get; set; }
        public string EmergencyContact { get; set; }
        public string EmergencyAddress { get; set; }
        public string EmpFacebook { get; set; }
        public string EmpTwitter { get; set; }
        public string EmpLinkedin { get; set; }
        public Nullable<int> EmpHiringMethodId { get; set; }
        public string EmpCitizenshipNumber { get; set; }
        public string EmpCitizenshipIssuDate { get; set; }
        public Nullable<int> EmpCitizenshipDistrictId { get; set; }
        public string NomineeName { get; set; }
        public string NomineeAddress { get; set; }
        public string NomineePhoto { get; set; }
        public Nullable<System.DateTime> NomineeDob { get; set; }
        public string NomineeCitizenshipNumber { get; set; }
        public Nullable<System.DateTime> NomineeCitizenshipIssuDate { get; set; }
        public Nullable<int> NomineeCitizenshipIssueDistrictId { get; set; }
        public string NomineeRelation { get; set; }
        public string Nationality { get; set; }
        public string SpouseName { get; set; }
        public string EmployeeHeight { get; set; }
        public Nullable<System.DateTime> PfEffectiveDate { get; set; }
        public Nullable<System.DateTime> GratuityEffectiveDate { get; set; }
        public string EmployeeBankAccountNumber { get; set; }
    }
}
