//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSkill
    {
        public int Id { get; set; }
        public int EmpCode { get; set; }
        public int EmpSkillId { get; set; }
        public Nullable<int> EmpSkillPoint { get; set; }
        public Nullable<bool> EmpSkillStatus { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
