//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeExperience
    {
        public int ExpId { get; set; }
        public int EmpCode { get; set; }
        public string CompanyName { get; set; }
        public string CompanyContact { get; set; }
        public string Designation { get; set; }
        public string JobDescription { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EnDate { get; set; }
        public string RefName { get; set; }
        public string RefDesignation { get; set; }
        public string RefEmail { get; set; }
        public string RefPhone { get; set; }
        public Nullable<bool> Verified { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
