//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDocument
    {
        public int DocumentId { get; set; }
        public int DocumentEmpCode { get; set; }
        public Nullable<int> DocumentCatId { get; set; }
        public string DocumentTitle { get; set; }
        public Nullable<bool> DocumentOnlyAdmin { get; set; }
        public Nullable<bool> DocumentVerified { get; set; }
        public string DocumentRemarks { get; set; }
        public Nullable<System.DateTime> DocumentCreatedAt { get; set; }
    
        public virtual DocumentCategory DocumentCategory { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
