//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAddress
    {
        public int Id { get; set; }
        public int EmployeeCode { get; set; }
        public int HouseNumber { get; set; }
        public int WardNumber { get; set; }
        public string VDC { get; set; }
        public int District { get; set; }
        public int Zone { get; set; }
        public string State { get; set; }
        public int Country { get; set; }
        public string LandMark { get; set; }
        public string AddressType { get; set; }
    
        public virtual Country Country1 { get; set; }
        public virtual District District1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Zone Zone1 { get; set; }
    }
}
