//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeJobHistory
    {
        public int HistoryId { get; set; }
        public int EmpCode { get; set; }
        public int OfficeId { get; set; }
        public int DeptId { get; set; }
        public int SectionId { get; set; }
        public int DesgId { get; set; }
        public int RankId { get; set; }
        public int GradeNumber { get; set; }
        public int LevelId { get; set; }
        public int BusinessGroupId { get; set; }
        public int ShiftId { get; set; }
        public Nullable<int> RemoteId { get; set; }
        public int JobTypeId { get; set; }
        public int ServiceEventGroupId { get; set; }
        public Nullable<int> ServiceEventSubGroupId { get; set; }
        public Nullable<bool> DesgKayamMukayamMuKaRaRa { get; set; }
        public string ServiceEvent { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ServiceHolidingDate { get; set; }
        public Nullable<System.DateTime> DecisionDate { get; set; }
        public string LetterRefNo { get; set; }
        public Nullable<System.DateTime> LetterIssueDate { get; set; }
        public Nullable<System.DateTime> EffectiveTillDate { get; set; }
        public Nullable<System.DateTime> OfficeJoinDate { get; set; }
        public string Remarks { get; set; }
        public string Instruction { get; set; }
        public Nullable<int> SadarGarneEmployeeCode { get; set; }
        public Nullable<System.DateTime> SadarDate { get; set; }
        public string KaajType { get; set; }
        public Nullable<System.DateTime> KajStartDate { get; set; }
        public Nullable<System.DateTime> KajEndDate { get; set; }
        public string ChalaniNumber { get; set; }
        public string RemoteCode { get; set; }
    
        public virtual BusinessGroup BusinessGroup { get; set; }
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual EmployeeJobHistory EmployeeJobHistories1 { get; set; }
        public virtual EmployeeJobHistory EmployeeJobHistory1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual JobType JobType { get; set; }
        public virtual Level Level { get; set; }
        public virtual Office Office { get; set; }
        public virtual RemoteArea RemoteArea { get; set; }
        public virtual Section Section { get; set; }
        public virtual ServiceEventGroup ServiceEventGroup { get; set; }
        public virtual ServiceEventSubGroup ServiceEventSubGroup { get; set; }
        public virtual Shift Shift { get; set; }
    }
}
