//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEducation
    {
        public int EduId { get; set; }
        public int EmpCode { get; set; }
        public int EmpEduLevelId { get; set; }
        public string DegreeName { get; set; }
        public string FacultyName { get; set; }
        public Nullable<System.DateTime> PassedDate { get; set; }
        public int CountryId { get; set; }
        public string UniversityName { get; set; }
        public string MarkingSystem { get; set; }
        public string ObtainedMark { get; set; }
        public string ScanDocument { get; set; }
        public byte EducationStatus { get; set; }
        public string Division { get; set; }
        public string ObtainedMarks { get; set; }
    }
}
