//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EmployeeAddresses = new HashSet<EmployeeAddress>();
            this.EmployeeBanks = new HashSet<EmployeeBank>();
            this.EmployeeDocuments = new HashSet<EmployeeDocument>();
            this.EmployeeExperiences = new HashSet<EmployeeExperience>();
            this.EmployeeFamilies = new HashSet<EmployeeFamily>();
            this.EmployeeGradeUpdates = new HashSet<EmployeeGradeUpdate>();
            this.EmployeeJobHistories = new HashSet<EmployeeJobHistory>();
            this.EmployeeJobHistories1 = new HashSet<EmployeeJobHistory>();
            this.EmployeePrizes = new HashSet<EmployeePrize>();
            this.PayrollSalaryTables = new HashSet<PayrollSalaryTable>();
            this.PayrollArrears = new HashSet<PayrollArrear>();
            this.EmployeeSkills = new HashSet<EmployeeSkill>();
            this.EmpTrainings = new HashSet<EmpTraining>();
            this.LeaveApplications = new HashSet<LeaveApplication>();
            this.LeaveApplications1 = new HashSet<LeaveApplication>();
            this.LeaveApplications2 = new HashSet<LeaveApplication>();
            this.LeaveEarneds = new HashSet<LeaveEarned>();
            this.LeaveEarneds1 = new HashSet<LeaveEarned>();
            this.LeaveEarneds2 = new HashSet<LeaveEarned>();
            this.Offices = new HashSet<Office>();
            this.PayrollInsurancePremiums = new HashSet<PayrollInsurancePremium>();
            this.PayrollIntrestGains = new HashSet<PayrollIntrestGain>();
            this.PayrollLeaveDeductions = new HashSet<PayrollLeaveDeduction>();
            this.PayrollOvertimes = new HashSet<PayrollOvertime>();
            this.PayrollSalaryMasterSheets = new HashSet<PayrollSalaryMasterSheet>();
        }
    
        public int EmpCode { get; set; }
        public string CustomerId { get; set; }
        public string EmpDisplayCode { get; set; }
        public int EmpOfficeId { get; set; }
        public int EmpLevelId { get; set; }
        public int EmpRankId { get; set; }
        public int EmpShiftId { get; set; }
        public int EmpDeptId { get; set; }
        public int EmpSectionId { get; set; }
        public int EmpDesgId { get; set; }
        public int EmpTypeId { get; set; }
        public int EmpBgId { get; set; }
        public int EmpJobTypeId { get; set; }
        public Nullable<int> EmpLeaveRuleId { get; set; }
        public int EmpRoleId { get; set; }
        public Nullable<int> EmpGradeStartNumber { get; set; }
        public Nullable<int> CurrentGrade { get; set; }
        public Nullable<int> CurrentGrade_Test { get; set; }
        public Nullable<bool> EmpDeptHead { get; set; }
        public Nullable<bool> EmpOfficeHead { get; set; }
        public string EmpName { get; set; }
        public string EmpEmail { get; set; }
        public string EmpUserName { get; set; }
        public string EmpPassword { get; set; }
        public string EmpPhoto { get; set; }
        public string EmpGender { get; set; }
        public string EmpMaritalStatus { get; set; }
        public Nullable<bool> EmpIncapacitated { get; set; }
        public Nullable<bool> EmpStatus { get; set; }
        public Nullable<System.DateTime> EmpAppointmentDate { get; set; }
        public Nullable<System.DateTime> EmpCurrentRankAppDate { get; set; }
        public Nullable<System.DateTime> EmpCreatedDate { get; set; }
        public Nullable<System.DateTime> EmpContractExpiryDate { get; set; }
        public Nullable<System.DateTime> EmpResignedDate { get; set; }
        public Nullable<bool> EmpAttendanceIgnore { get; set; }
        public Nullable<bool> EmpPayroll { get; set; }
        public Nullable<int> EmpJobHistoryId { get; set; }
        public string EmpRemoteType { get; set; }
        public Nullable<int> EmpTaxSetupId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual Designation Designation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAddress> EmployeeAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeBank> EmployeeBanks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeDocument> EmployeeDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeExperience> EmployeeExperiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeFamily> EmployeeFamilies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeGradeUpdate> EmployeeGradeUpdates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeJobHistory> EmployeeJobHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeJobHistory> EmployeeJobHistories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePrize> EmployeePrizes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollSalaryTable> PayrollSalaryTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollArrear> PayrollArrears { get; set; }
        public virtual Employee Employees1 { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual JobType JobType { get; set; }
        public virtual LeaveRule LeaveRule { get; set; }
        public virtual LeaveRule LeaveRule1 { get; set; }
        public virtual Level Level { get; set; }
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSkill> EmployeeSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpTraining> EmpTrainings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveApplication> LeaveApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveApplication> LeaveApplications1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveApplication> LeaveApplications2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveEarned> LeaveEarneds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveEarned> LeaveEarneds1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveEarned> LeaveEarneds2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Office> Offices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollInsurancePremium> PayrollInsurancePremiums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollIntrestGain> PayrollIntrestGains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollLeaveDeduction> PayrollLeaveDeductions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollOvertime> PayrollOvertimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollSalaryMasterSheet> PayrollSalaryMasterSheets { get; set; }
    }
}
