//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpTraining
    {
        public int Id { get; set; }
        public int EmpCode { get; set; }
        public string TrainingTitle { get; set; }
        public string TrainingFocus { get; set; }
        public Nullable<System.DateTime> LetterDate { get; set; }
        public System.DateTime TrainingStartDate { get; set; }
        public System.DateTime TrainingEndDate { get; set; }
        public System.DateTime TrainingVisitStartDate { get; set; }
        public System.DateTime TrainingVisitEndDate { get; set; }
        public string TrainingOrganization { get; set; }
        public int Designation { get; set; }
        public int Rank { get; set; }
        public int Office { get; set; }
        public string NationalInternational { get; set; }
        public int TrainingCountry { get; set; }
        public string TrainingVenue { get; set; }
        public string Sponsorship { get; set; }
        public string SponsorerOrganizationName { get; set; }
        public int Approver { get; set; }
    
        public virtual Designation Designation1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Office Office1 { get; set; }
        public virtual Rank Rank1 { get; set; }
    }
}
