//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fiscal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fiscal()
        {
            this.PayrollArrears = new HashSet<PayrollArrear>();
            this.PayrollSalaryTables = new HashSet<PayrollSalaryTable>();
            this.PayrollMonthDescriptions = new HashSet<PayrollMonthDescription>();
        }
    
        public int FyId { get; set; }
        public string FyName { get; set; }
        public System.DateTime FyStartDate { get; set; }
        public System.DateTime FyEndDate { get; set; }
        public string FyStartDateNp { get; set; }
        public string FyEndDateNp { get; set; }
        public bool FyCurrent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollArrear> PayrollArrears { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollSalaryTable> PayrollSalaryTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollMonthDescription> PayrollMonthDescriptions { get; set; }
    }
}
