//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Holiday()
        {
            this.HolidayAssignedOffices = new HashSet<HolidayAssignedOffice>();
        }
    
        public int HolidayId { get; set; }
        public string HolidayTitle { get; set; }
        public string HolidayDescription { get; set; }
        public System.DateTime HolidayDate { get; set; }
        public bool HolidayYearlyOccourence { get; set; }
        public Nullable<System.DateTime> HolidayFiscalYear { get; set; }
        public int HolidayOfficeId { get; set; }
        public int HolidayReligionId { get; set; }
        public int HolidayEthnicityId { get; set; }
        public string HolidayGender { get; set; }
        public bool HolidayStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HolidayAssignedOffice> HolidayAssignedOffices { get; set; }
    }
}
