//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveEarned
    {
        public int LeaveEarnedId { get; set; }
        public int EmpCode { get; set; }
        public Nullable<System.DateTime> LeaveEarnRequestedDate { get; set; }
        public Nullable<int> RecommendedEmpCode { get; set; }
        public string RecommendStatus { get; set; }
        public Nullable<System.DateTime> RecommendStatusDate { get; set; }
        public int ApproverEmpCode { get; set; }
        public Nullable<int> ApproverStatus { get; set; }
        public Nullable<System.DateTime> ApproverStatusDate { get; set; }
        public System.DateTime WorkedStartDate { get; set; }
        public System.DateTime WorkedEndDate { get; set; }
        public Nullable<decimal> LeaveTotalEanrnedDays { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
        public Nullable<System.DateTime> EarnLeaveExpiryDate { get; set; }
        public string Remarks { get; set; }
        public int LeaveYearId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual LeaveType LeaveType { get; set; }
        public virtual LeaveYear LeaveYear { get; set; }
    }
}
