//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRuleDetail
    {
        public int DetailId { get; set; }
        public int LeaveRuleId { get; set; }
        public int LeaveTypeId { get; set; }
        public Nullable<decimal> LeaveDays { get; set; }
    
        public virtual LeaveRule LeaveRule { get; set; }
        public virtual LeaveType LeaveType { get; set; }
    }
}
