//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveYearlyProcess
    {
        public int ProcessId { get; set; }
        public int PrevLeavYearId { get; set; }
        public int LeaveYearId { get; set; }
        public Nullable<int> ProcessByEmpCode { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
    }
}
