//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeaveType()
        {
            this.LeaveApplications = new HashSet<LeaveApplication>();
            this.LeaveAssigneds = new HashSet<LeaveAssigned>();
            this.LeaveEarneds = new HashSet<LeaveEarned>();
            this.LeaveRuleDetails = new HashSet<LeaveRuleDetail>();
            this.PayrollLeaveDeductions = new HashSet<PayrollLeaveDeduction>();
        }
    
        public int LeaveTypeId { get; set; }
        public string LeaveTypeName { get; set; }
        public string LeaveTypeDescription { get; set; }
        public Nullable<byte> NumberOfTime { get; set; }
        public Nullable<bool> IsPayable { get; set; }
        public Nullable<bool> IsCashable { get; set; }
        public Nullable<int> MaxCashable { get; set; }
        public Nullable<bool> IsTransferable { get; set; }
        public Nullable<int> MaxTransferable { get; set; }
        public Nullable<int> MonthlyQty { get; set; }
        public Nullable<int> LeaveApplyBefore { get; set; }
        public string MaritalStatus { get; set; }
        public string Gender { get; set; }
        public Nullable<decimal> ProRataLeaveRatio { get; set; }
        public string LeaveTypeAssignment { get; set; }
        public Nullable<int> LeaveDeductionPriority { get; set; }
        public Nullable<byte> LeaveCalculation { get; set; }
        public string LeaveType1 { get; set; }
        public bool HalfdayAllow { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveApplication> LeaveApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveAssigned> LeaveAssigneds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveEarned> LeaveEarneds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveRuleDetail> LeaveRuleDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollLeaveDeduction> PayrollLeaveDeductions { get; set; }
    }
}
