//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveAssigned
    {
        public int AssignedId { get; set; }
        public int AssignEmpCode { get; set; }
        public int AssignLeaveTypeId { get; set; }
        public Nullable<decimal> AssignedDays { get; set; }
        public Nullable<decimal> LeaveTakenDays { get; set; }
        public Nullable<int> AssignedLeaveYearId { get; set; }
        public string AssignedRemarks { get; set; }
        public Nullable<int> LeaveGainedMonth { get; set; }
    
        public virtual LeaveAssigned LeaveAssigned1 { get; set; }
        public virtual LeaveAssigned LeaveAssigned2 { get; set; }
        public virtual LeaveType LeaveType { get; set; }
        public virtual LeaveYear LeaveYear { get; set; }
        public virtual LeaveYear LeaveYear1 { get; set; }
    }
}
