//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationDistrict
    {
        public int DistrictId { get; set; }
        public Nullable<int> DistrictZoneId { get; set; }
        public Nullable<int> DistrictPradeshId { get; set; }
        public string DistrictName { get; set; }
    }
}
