//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long MsgId { get; set; }
        public int MsgReceiverId { get; set; }
        public string MsgReceiverType { get; set; }
        public string MsgSubject { get; set; }
        public string MsgText { get; set; }
        public Nullable<System.DateTime> MsgSentDate { get; set; }
        public Nullable<System.DateTime> MsgReadDate { get; set; }
        public string MsgSenderType { get; set; }
        public int MsgSenderId { get; set; }
        public string MsgAttachment { get; set; }
    }
}
