//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Office()
        {
            this.EmployeeJobHistories = new HashSet<EmployeeJobHistory>();
            this.Employees = new HashSet<Employee>();
            this.EmpTrainings = new HashSet<EmpTraining>();
            this.HolidayAssignedOffices = new HashSet<HolidayAssignedOffice>();
            this.PayrollSalaryTables = new HashSet<PayrollSalaryTable>();
            this.PayrollSalaryMasterSheets = new HashSet<PayrollSalaryMasterSheet>();
        }
    
        public int OfficeId { get; set; }
        public Nullable<int> OfficeParentId { get; set; }
        public string OfficeCode { get; set; }
        public string OfficeName { get; set; }
        public string OfficeAddress { get; set; }
        public string OfficePhone { get; set; }
        public string OfficeGeoLocation { get; set; }
        public Nullable<bool> OfficeStatus { get; set; }
        public Nullable<int> OfficeTypeId { get; set; }
        public Nullable<int> OfficeLocationId { get; set; }
        public bool IsActive { get; set; }
        public int PayrollRemmoteSetupRemoteId { get; set; }
        public Nullable<int> OfficeHeadEmpCode { get; set; }
        public Nullable<int> ApprisalRegion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeJobHistory> EmployeeJobHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpTraining> EmpTrainings { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HolidayAssignedOffice> HolidayAssignedOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollSalaryTable> PayrollSalaryTables { get; set; }
        public virtual Office Offices1 { get; set; }
        public virtual Office Office1 { get; set; }
        public virtual PayrollRemoteSetup PayrollRemoteSetup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollSalaryMasterSheet> PayrollSalaryMasterSheets { get; set; }
    }
}
