//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollRemoteAllowance
    {
        public int RAId { get; set; }
        public int RARankId { get; set; }
        public int RARemoteId { get; set; }
        public decimal RemoteAllowance { get; set; }
        public string RAType { get; set; }
    
        public virtual PayrollRemoteSetup PayrollRemoteSetup { get; set; }
        public virtual Rank Rank { get; set; }
    }
}
