//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollAttendanceMonthly
    {
        public int Id { get; set; }
        public int FyId { get; set; }
        public int MonthId { get; set; }
        public int PayrollSalaryTableId { get; set; }
        public int EmployeeCode { get; set; }
        public decimal TotalWorkingDays { get; set; }
        public decimal NoOfDaysInAttendanceTable { get; set; }
        public decimal IsAbsent { get; set; }
        public decimal IsWeekend { get; set; }
        public decimal IsHoliday { get; set; }
        public decimal TotalPaidLeave { get; set; }
        public decimal TotalUnpaidLeave { get; set; }
    }
}
