//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class payrollLeaveDay
    {
        public int LeaveId { get; set; }
        public int LeaveEmpCode { get; set; }
        public System.DateTime LeaveDate { get; set; }
        public decimal LeavePayableDays { get; set; }
        public int LeaveApplicationId { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
        public Nullable<decimal> LeaveDays { get; set; }
    }
}
