//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollInsurancePremium
    {
        public int IsuranceClaimId { get; set; }
        public int InsuranceCompanyId { get; set; }
        public decimal InsuredAmount { get; set; }
        public Nullable<decimal> PremiumAmount { get; set; }
        public string AmountType { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> InsuranceClaimFyId { get; set; }
        public int EmpCode { get; set; }
        public string InsurancePolicyNumber { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual InsuranceCompany InsuranceCompany { get; set; }
    }
}
