//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollAllowanceMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PayrollAllowanceMaster()
        {
            this.PayrollAllowanceDetails = new HashSet<PayrollAllowanceDetail>();
        }
    
        public int AllowanceMasterId { get; set; }
        public string AllowanceKey { get; set; }
        public string AllowanceName { get; set; }
        public string AllowanceType { get; set; }
        public string EarningDeduction { get; set; }
        public string PercentageAmount { get; set; }
        public decimal Value { get; set; }
        public bool IsAlwaysAplicable { get; set; }
        public bool ApplyToAllEmployee { get; set; }
        public bool IsPerDayDeductable { get; set; }
        public bool SameForAllEmployee { get; set; }
        public bool GivenOnlyIfPresent { get; set; }
        public bool IsTaxable { get; set; }
        public bool IsActive { get; set; }
        public bool IsDefault { get; set; }
        public Nullable<System.DateTime> ApplicableFromDate { get; set; }
        public Nullable<System.DateTime> ApplicableToDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollAllowanceDetail> PayrollAllowanceDetails { get; set; }
    }
}
