//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollLeaveDeduction
    {
        public int DeductionId { get; set; }
        public int EmpCode { get; set; }
        public int LeaveTypeId { get; set; }
        public decimal LeaveDays { get; set; }
        public string DeductionType { get; set; }
        public Nullable<int> LeaveYearId { get; set; }
        public System.DateTime LeaveDate { get; set; }
        public string Details { get; set; }
        public bool isEncashed { get; set; }
        public Nullable<int> ActionMonthId { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual LeaveType LeaveType { get; set; }
        public virtual LeaveYear LeaveYear { get; set; }
    }
}
