//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollMonthDescription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PayrollMonthDescription()
        {
            this.PayrollArrears = new HashSet<PayrollArrear>();
            this.PayrollArrears1 = new HashSet<PayrollArrear>();
            this.PayrollSalaryTables = new HashSet<PayrollSalaryTable>();
        }
    
        public int Id { get; set; }
        public int FyId { get; set; }
        public int MonthIndex { get; set; }
        public string MonthNameEnglish { get; set; }
        public string MonthNameNepali { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public decimal WorkingDays { get; set; }
    
        public virtual Fiscal Fiscal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollArrear> PayrollArrears { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollArrear> PayrollArrears1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollSalaryTable> PayrollSalaryTables { get; set; }
    }
}
