//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollIntrestGain
    {
        public int Id { get; set; }
        public Nullable<int> EmpCode { get; set; }
        public string CustomerId { get; set; }
        public Nullable<int> FyId { get; set; }
        public Nullable<int> MonthIndex { get; set; }
        public Nullable<decimal> InterestGain { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
