//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollSalaryDetailSheet
    {
        public int Id { get; set; }
        public int AllowanceId { get; set; }
        public string AllowanceName { get; set; }
        public string AllowanceType { get; set; }
        public string EarningDeduction { get; set; }
        public string PercentageAmount { get; set; }
        public decimal Value { get; set; }
        public decimal CalculatedValue { get; set; }
        public int PayrollSalaryMasterId { get; set; }
    
        public virtual PayrollSalaryMasterSheet PayrollSalaryMasterSheet { get; set; }
    }
}
