//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollArrear
    {
        public int Id { get; set; }
        public int EmployeeCode { get; set; }
        public int ArrearMonth { get; set; }
        public int AdjustMonth { get; set; }
        public int FyId { get; set; }
        public string EarningDeduction { get; set; }
        public decimal NoOfDays { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Fiscal Fiscal { get; set; }
        public virtual PayrollMonthDescription PayrollMonthDescription { get; set; }
        public virtual PayrollMonthDescription PayrollMonthDescription1 { get; set; }
    }
}
