//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollSalaryTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PayrollSalaryTable()
        {
            this.PayrollSalaryMasterSheets = new HashSet<PayrollSalaryMasterSheet>();
        }
    
        public int Id { get; set; }
        public int FyId { get; set; }
        public int PayrollMonthId { get; set; }
        public int CreatorId { get; set; }
        public int OfficeId { get; set; }
        public Nullable<int> BgId { get; set; }
        public string Details { get; set; }
        public bool SalaryConfirmed { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Fiscal Fiscal { get; set; }
        public virtual Office Office { get; set; }
        public virtual PayrollMonthDescription PayrollMonthDescription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollSalaryMasterSheet> PayrollSalaryMasterSheets { get; set; }
        public virtual PayrollSalaryTable PayrollSalaryTable1 { get; set; }
        public virtual PayrollSalaryTable PayrollSalaryTable2 { get; set; }
    }
}
