//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollOvertime
    {
        public int OvertimeId { get; set; }
        public int EmpCode { get; set; }
        public System.DateTime OvertimeDate { get; set; }
        public string Subject { get; set; }
        public string Details { get; set; }
        public Nullable<int> ApprovedById { get; set; }
        public bool ApproveStatus { get; set; }
        public Nullable<System.DateTime> ApproveStatusDate { get; set; }
        public Nullable<decimal> OvertimeAmount { get; set; }
        public decimal OvertimeHours { get; set; }
        public Nullable<System.DateTime> OvertimeAppliedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
