//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollEmployeeSetup
    {
        public int EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public string CurrentEmployeeStatus { get; set; }
        public decimal CurrentBasicSalary { get; set; }
        public Nullable<decimal> DearnessAmount { get; set; }
        public Nullable<decimal> ActualBasicSalary { get; set; }
        public int CurrentGradeCode { get; set; }
        public int CurrentDesignationCode { get; set; }
        public int CurrentDepartmentCode { get; set; }
        public int CurrentBranchCode { get; set; }
        public string MaritialStatus { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string Gender { get; set; }
        public string AccountNo { get; set; }
        public string IsDisabled { get; set; }
        public string PanNo { get; set; }
    }
}
