//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rank()
        {
            this.EmpTrainings = new HashSet<EmpTraining>();
            this.PayrollRemoteAllowances = new HashSet<PayrollRemoteAllowance>();
        }
    
        public int RankId { get; set; }
        public Nullable<decimal> RankName { get; set; }
        public string RankDescription { get; set; }
        public Nullable<decimal> RankSalary { get; set; }
        public Nullable<decimal> RankMaxGrade { get; set; }
        public Nullable<decimal> RankPerGradeAmount { get; set; }
        public Nullable<decimal> BankAllowance { get; set; }
        public Nullable<decimal> Incentive { get; set; }
        public Nullable<decimal> SiteInchargeship { get; set; }
        public Nullable<decimal> UniformAllowance { get; set; }
        public Nullable<decimal> RankSpecialAllowance { get; set; }
        public Nullable<decimal> RankInchargeShipAllowance { get; set; }
        public Nullable<decimal> RankOtherAllowances { get; set; }
        public Nullable<decimal> OverTimeRate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpTraining> EmpTrainings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollRemoteAllowance> PayrollRemoteAllowances { get; set; }
    }
}
