//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftDay
    {
        public int DayId { get; set; }
        public int DayShiftId { get; set; }
        public int DayNumber { get; set; }
        public string DayName { get; set; }
        public Nullable<System.TimeSpan> DayStartTime { get; set; }
        public Nullable<System.TimeSpan> DayEndTime { get; set; }
        public bool DayDual { get; set; }
        public int DayWorkingMinute { get; set; }
        public bool DayWeekend { get; set; }
    
        public virtual Shift Shift { get; set; }
    }
}
