//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeHRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LeaveTotalAssigned
    {
        public int AssignEmpCode { get; set; }
        public Nullable<int> AssignedLeaveYearId { get; set; }
        public int AssignLeaveTypeId { get; set; }
        public Nullable<decimal> TotalLeave { get; set; }
    }
}
